# -*- coding: utf-8 -*-
"""Trabalho POO 07/04 - Ada Maris P. Mário

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1p6z27MaDqbMOnTSlQZzQmmw0gXhzl6y_
"""

def palindromo_numero():
  palindromo = 9009
  for i in range(100,1000):
    for j in range(100,1000):
      prod = i*j
      if str(prod) == str(prod)[::-1]:
        if prod > palindromo:
          palindromo = prod
  return palindromo

print(palindromo_numero())